### ISSUE TITLE
classifier.py 실행 오류

### ISSUE THREAD

**Issue by NotoriousH2** [kakao-arena/shopping-classification#7]
baseline 실행 중 아래 코드 진행 시 에러 메시지가 나면서 진행이 안되는데요. 어떻게 해결해야 할까요?
감사합니다.

~/shopping-classification$ **python classifier.py predict ./data/train ./model/train ./data/train/ dev predict.tsv**
Using TensorFlow backend.
[INFO    ] 2018-11-19 13:03:07 [classifier.py] [predict:95] # of classes(train): 4215
2018-11-19 13:03:07.412209: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-19 13:03:10.844034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2018-11-19 13:03:11.207138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2018-11-19 13:03:11.584640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 2 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:83:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2018-11-19 13:03:11.972980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 3 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:84:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2018-11-19 13:03:11.974668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2018-11-19 13:03:11.974761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1 2 3 
2018-11-19 13:03:11.974771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y N N 
2018-11-19 13:03:11.974778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y N N 
2018-11-19 13:03:11.974784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 2:   N N Y Y 
2018-11-19 13:03:11.974790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 3:   N N Y Y 
2018-11-19 13:03:11.974810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:02:00.0, compute capability: 6.1)
2018-11-19 13:03:11.974819: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: TITAN Xp, pci bus id: 0000:04:00.0, compute capability: 6.1)
2018-11-19 13:03:11.974826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:2) -> (device: 2, name: TITAN Xp, pci bus id: 0000:83:00.0, compute capability: 6.1)
2018-11-19 13:03:11.974833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:3) -> (device: 3, name: TITAN Xp, pci bus id: 0000:84:00.0, compute capability: 6.1)
   2/1587 [..............................] - ETA: 293sException in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
ValueError: generator already executing

Traceback (most recent call last):
  File "classifier.py", line 163, in <module>
    'predict': clsf.predict})
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "classifier.py", line 109, in predict
    verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2272, in predict_generator
    generator_output = next(output_generator)
StopIteration

**Comment by GzuPark** [comment]
https://arena.kakao.com/forum/t/prediction/84

참고하시면 좋을 것 같습니다.
그리고, basecode는 `tensorflow-gpu`가 아닌 `tensorflow`를 사용하였고, 시스템 RAM이 16G 이상이라면 정상적으로 동작합니다.

**Comment by ummae** [comment]
@NotoriousH2 어떤 브랜치의 코드로 테스트하셨나요? 방금 `dev` 브랜치의 내용을 `master`로 머지했습니다. `master` 코드를 업데이트 하신 후에 다시 한번 테스트 해주세요. 실행 스팩과 관련해서는 여기 https://github.com/kakao-arena/shopping-classification#benchmark 내용 참고 부탁드립니다.

**Comment by NotoriousH2** [comment]
업데이트 후에 정상 작동됩니다. 감사합니다.
